// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// GENERATED by scripts/dictionaries/build.mjs — do not edit by hand.
// oss-spec:allow-large-file: generated dictionary data, one entry per line
// The 300 largest localities whose name is also an everyday
// Swedish word ("Lund", "Bro", "Vara"); smaller ones are dropped. A detector
// only trusts these mid-sentence, where an ordinary word is not capitalised.
export default [
  "Bro",
  "Fristad",
  "Gråbo",
  "Grästorp",
  "Herrljunga",
  "Kil",
  "Kungsbacka",
  "Kungshamn",
  "Köping",
  "Landskrona",
  "Leksand",
  "Ljusdal",
  "Lomma",
  "Lund",
  "Mora",
  "Nacka",
  "Skara",
  "Strömstad",
  "Strömsund",
  "Söderhamn",
  "Trollhättan",
  "Vara",
  "Ödeshög",
] as const;
