// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// How a surname is recognised. The dictionary (SCB's surnames with at least
// 100 bearers, see `./data/`) is the strongest signal; beyond it, a
// capitalised word with a characteristic Swedish ending (-sson, -berg,
// -ström, …) counts too, minus a stop-list of ordinary words that end the
// same way and of the titles and function words that precede a name.

import { dictionaries } from "./dictionaries.ts";

export const SURNAME_SUFFIXES: readonly string[] = [
  "sson",
  "son",
  "berg",
  "borg",
  "ström",
  "strom",
  "lund",
  "gren",
  "qvist",
  "quist",
  "kvist",
  "mark",
  "man",
  "dahl",
  "holm",
  "stedt",
  "ander",
  "én",
  "feldt",
  "vall",
  "wall",
  "hammar",
  "bäck",
  "strand",
  "blad",
  "löv",
  "sjö",
  "ius",
  "gård",
  "lind",
  "bom",
  "stam",
  "torp",
  "fors",
  "fält",
  "hed",
  "vik",
  "wik",
];

/** Capitalised everyday words that end like a surname, plus the titles,
 *  roles, and sentence-initial function words that precede a name. */
export const NOT_SURNAMES: ReadonlySet<string> = new Set([
  "Person",
  "Personer",
  "Personen",
  "Tjänsteman",
  "Tjänstemän",
  "Ombudsman",
  "Talman",
  "Förman",
  "Nämndeman",
  "Brandman",
  "Polisman",
  "Gärningsman",
  "Målsman",
  "Fackman",
  "Sjöman",
  "Statsman",
  "Landsman",
  "Affärsman",
  "Idrottsman",
  "Länsman",
  "Danmark",
  "Lappmark",
  "Bergen",
  "Norrland",
  "Finland",
  "Island",
  "Holland",
  "Tyskland",
  "England",
  "Ryssland",
  "Estland",
  "Lettland",
  "Skottland",
  "Irland",
  "Grekland",
  "Svealand",
  "Götaland",
  "Kalender",
  "Salamander",
  "Meander",
  "Sedan",
  "Kanske",
  "Sedermera",
  "Anledning",
  "Sjukhus",
  "Skandal",
  "Modell",
  "Hotell",
  "Detaljplan",
  "Beslut",
  "Nyheter",
  "Nyhet",
  "Stockholm",
  "Lidingö",
  "Kungsholmen",
  "Vasastan",
  "Södermalm",
  "Östermalm",
  "Hisingen",
  "Handelsbanken",
  "Swedbank",
  "Nordea",
  "Riksbanken",
  "Regeringen",
  "Riksdagen",
  "Domstolen",
  "Nämnden",
  "Kommunen",
  "Landstinget",
  "Regionen",
  "Myndigheten",
  "Förvaltningen",
  "Utskottet",
  "Sverige",
  "Sveriges",
  "Skåne",
  "Halland",
  "Blekinge",
  "Småland",
  "Dalarna",
  "Gästrikland",
  "Hälsingland",
  "Medelpad",
  "Ångermanland",
  "Västerbotten",
  "Norrbotten",
  "Lappland",
  "Jämtland",
  "Härjedalen",
  "Värmland",
  "Närke",
  "Västmanland",
  "Uppland",
  "Södermanland",
  "Östergötland",
  "Västergötland",
  "Dalsland",
  "Bohuslän",
  "Gotland",
  "Öland",
  "Norden",
  "Sverigedemokraterna",
  "Moderaterna",
  "Socialdemokraterna",
  "Centerpartiet",
  "Liberalerna",
  "Vänsterpartiet",
  "Kristdemokraterna",
  "Miljöpartiet",
  "Kronan",
  "Torsdag",
  "Tisdag",
  "Måndag",
  "Onsdag",
  "Fredag",
  "Lördag",
  "Söndag",
  "Januari",
  "Februari",
  "Mars",
  "April",
  "Juni",
  "Juli",
  "Augusti",
  "September",
  "Oktober",
  "November",
  "December",
  "Hej",
  "Med",
  "Bästa",
  "Hälsningar",
  "Vänliga",
  "Angående",
  "Ärende",
  "Avsändare",
  "Mottagare",
  "Datum",
  "Namn",
  "Adress",
  "Telefon",
  "Postnummer",
  "Ort",
  "Personnummer",
  "Kommun",
  "Län",
  "Ansökan",
  "Anmälan",
  "Beslutet",
  "Överklagan",
  "Bilaga",
  "Bilagor",
  "Sammanfattning",
  "Bakgrund",
  "Fråga",
  "Svar",
  "Handläggare",
  "Sökande",
  "Sökanden",
  "Klaganden",
  "Motpart",
  "Vårdnadshavare",
  "Förälder",
  "Barnet",
  "Eleven",
  "Patienten",
  "Brukaren",
  "Kunden",
  "Ordförande",
  "Sekreterare",
  "Justerare",
  "Protokoll",
  "Beslutsunderlag",
  "Diarienummer",
  "Dnr",
  "Ref",
  "Referens",
  "Mvh",
  "Ps",
  "Obs",
  // titles and roles that precede a name
  "Familjen",
  "Familj",
  "Herr",
  "Fru",
  "Fröken",
  "Doktor",
  "Dr",
  "Professor",
  "Advokat",
  "Läkare",
  "Rektor",
  "Lärare",
  "Chef",
  "Kurator",
  "Sjuksköterska",
  "Socialsekreterare",
  "Ombud",
  "Förvaltare",
  "Överförmyndare",
  "Kontaktperson",
  "Kontakt",
  "Mamma",
  "Pappa",
  "Mor",
  "Far",
  "Dotter",
  "Bror",
  "Syster",
  "Make",
  "Maka",
  "Sambo",
  "Partner",
  "Vän",
  "Granne",
  "Kollega",
  "Vittne",
  "Målsägande",
  "Tilltalad",
  "Fullmäktig",
  // sentence-initial function words that would otherwise read as a name
  "Enligt",
  "Från",
  "Till",
  "För",
  "Hos",
  "Vid",
  "Om",
  "Att",
  "Det",
  "Den",
  "Han",
  "Hon",
  "Hen",
  "Vi",
  "Ni",
  "De",
  "Dem",
  "Jag",
  "Du",
  "Efter",
  "Under",
  "Över",
  "Mellan",
  "Utan",
  "Innan",
  "När",
  "Var",
  "Vem",
  "Hur",
  "Varför",
  "Eftersom",
  "Även",
  "Också",
  "Bara",
  "Både",
  "Samt",
  "Eller",
  "Men",
  "Så",
  "Ja",
  "Nej",
  "Tack",
  "Hejsan",
  "Kontakta",
  "Se",
  "Bifogat",
  "Bifogar",
  "Här",
  "Där",
  "Detta",
  "Denna",
  "Dessa",
  "Vilket",
  "Vilken",
  "Vilka",
  "Alla",
  "Ingen",
  "Inget",
  "Inga",
  "Något",
  "Någon",
  "Några",
  "Mer",
  "Mest",
  "Idag",
  "Imorgon",
  "Igår",
  "Nu",
  "Sedan",
  "Snart",
]);

const LOWER_SUFFIXES = SURNAME_SUFFIXES.map((s) => s.toLowerCase());

/** Does a capitalised token end like a Swedish surname? */
export function hasSurnameEnding(token: string): boolean {
  if (token.length < 5) return false;
  if (!/^[\p{Lu}][\p{Ll}]+$/u.test(token)) return false;
  const lower = token.toLowerCase();
  return LOWER_SUFFIXES.some(
    (suf) => lower.endsWith(suf) && lower.length - suf.length >= 2,
  );
}

export type SurnameStrength = "strong" | "weak" | "none";

/** How confidently a capitalised token reads as a surname on its own:
 *  `strong` — in the dictionary or with a surname ending; `weak` — in the
 *  dictionary but also an everyday word (needs context); `none`. */
export function surnameStrength(token: string): SurnameStrength {
  if (NOT_SURNAMES.has(token)) return "none";
  const d = dictionaries();
  if (d.surnames.has(token) || hasSurnameEnding(token)) return "strong";
  if (d.surnamesWordLike.has(token)) return "weak";
  return "none";
}

export const looksLikeSurname = (token: string): boolean =>
  surnameStrength(token) === "strong";
